### PR TITLE
Add a bit of troushleshooting help for WINE users

### PR DESCRIPTION
**Pull request by Stasmo**

### CODE REVIEW

**Comment by Stasmo** [comment]
On second thought, this is not good advice.

**Comment by mcclure** [comment]
Hm, okay. I was actually going to accept it. Is there some better advice you can provide that we could put in the README or web page?

**Comment by Stasmo** [comment]
Sorry, my focus has shifted towards getting a version of snes9x-rr to compile on my debian box.

**Comment by mcclure** [comment]
Awesome

**Pull request closed without merging**
